name: Erlang CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 ct
    - name: Run xref
      run: rebar3 xref
    - name: Run elvis
      run: make elvis_rock

  dialyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run dialyzer
      run: rebar3 dialyzer
